### ISSUE TITLE
Compiling under Mac broken since 91cc968

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/libstorj-c#84]
With the beginning of this commit
https://github.com/Storj/libstorj-c/commit/91cc968b0c3d8629c7206199b93ceb92a76049bb

i am not able to compile it under macOS anymore. It fails with.

```
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall -g -static  -o storj cli.o ../src/libstorj.la 
libtool: link: gcc -g -O2 -Wall -g -o storj cli.o  ../src/.libs/libstorj.a -lneon -lnettle -ljson-c -luv -lm
Undefined symbols for architecture x86_64:
  "_aligned_alloc", referenced from:
      _storj_init_env in libstorj.a(storj.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [storj] Error 1
make: *** [all-recursive] Error 1
```

**Comment by braydonf** [comment]
We may need to test for `posix_memalign` and `aligned_alloc`, and use accordingly.
